server:
  port: 8081 # 项目启动的端口

spring:
  profiles:
    active: dev # 默认激活 dev 本地开发环境
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB

storage:
  type: minio # 对象存储类型


